version: '3.8'

services:
  aplist-api:
    build: .
    ports:
      - "8000:8001"
    env_file:
      - .env
    environment:
      - APP_MODE=aplist
    volumes:
      - ./app/data:/workspace/app/data
    networks:
      - ap-net

  template-api:
    build: .
    env_file:
      - .env
    environment:
      - APP_MODE=template
    volumes:
      - ./app/data:/workspace/app/data
    networks:
      - ap-net

networks:
  ap-net:
    driver: bridge