services:
  aplist-api:
    build: .
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - APP_MODE=aplist
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app/data:/workspace/app/data
    networks:
      - ap-net

  template-api:
    build: .
    env_file:
      - .env
    environment:
      - APP_MODE=template
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app/data:/workspace/app/data
    networks:
      - ap-net

networks:
  ap-net:
    driver: bridge