apiVersion: v1
kind: Service
metadata:
  name: template-api
  labels:
    io.kompose.service: template-api
spec:
  selector:
    io.kompose.service: template-api
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP